feat: add GetStockAtTick to database
fantasymarket/fantasymarket-api pull request #36
Opened 2020-07-06 16:52 UTC by explodingcamera

Closing #33

2020-07-06 16:58 UTC, juandogels commented
seems good to me but u can maybe use stock symbol instead of stock id, tests would also be nice

2020-07-06 17:04 UTC, Alyks1 commented
Yea, as Juandogels said, you should use the Symbol instead of the ID in the query

2020-07-06 17:18 UTC, explodingcamera commented
@juandogels we could maybe write some tests together tomorrow. The function now supports both the ID and symbols.

2020-07-06 18:57 UTC, juandogels commented
alright im down

2020-07-12 14:38 UTC, Alyks1 requested changes
Generally looks good. I flagged something unclear

2020-07-12 14:38 UTC, Alyks1 commented on database/database-stocks_test.go
> +		if test.needsToFail && assert.Error(err, "didnt't return the wrong tick") {
The error msg is quite hard to understand - should elaborate

2020-07-12 14:43 UTC, Alyks1 approved these changes

2020-07-12 14:44 UTC, merged